# Ex055 - Exception handling (1): try~handling

try:
    print('Hello.')
    print(param)
except:
    print('Exception has occurred!')
